
package org.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OperacionesAerolinea", targetNamespace = "http://ws.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OperacionesAerolinea {


    /**
     * 
     * @param origen
     * @param destino
     * @return
     *     returns java.util.List<org.ws.Vuelos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertainVuelos", targetNamespace = "http://ws.org/", className = "org.ws.GetCertainVuelos")
    @ResponseWrapper(localName = "getCertainVuelosResponse", targetNamespace = "http://ws.org/", className = "org.ws.GetCertainVuelosResponse")
    @Action(input = "http://ws.org/OperacionesAerolinea/getCertainVuelosRequest", output = "http://ws.org/OperacionesAerolinea/getCertainVuelosResponse")
    public List<Vuelos> getCertainVuelos(
        @WebParam(name = "origen", targetNamespace = "")
        String origen,
        @WebParam(name = "destino", targetNamespace = "")
        String destino);

    /**
     * 
     * @param idCliente
     * @param idVuelo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "comprarBoletoAgenciaUno", targetNamespace = "http://ws.org/", className = "org.ws.ComprarBoletoAgenciaUno")
    @ResponseWrapper(localName = "comprarBoletoAgenciaUnoResponse", targetNamespace = "http://ws.org/", className = "org.ws.ComprarBoletoAgenciaUnoResponse")
    @Action(input = "http://ws.org/OperacionesAerolinea/comprarBoletoAgenciaUnoRequest", output = "http://ws.org/OperacionesAerolinea/comprarBoletoAgenciaUnoResponse")
    public String comprarBoletoAgenciaUno(
        @WebParam(name = "id_vuelo", targetNamespace = "")
        String idVuelo,
        @WebParam(name = "id_cliente", targetNamespace = "")
        String idCliente);

    /**
     * 
     * @return
     *     returns java.util.List<org.ws.Vuelos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVuelos", targetNamespace = "http://ws.org/", className = "org.ws.GetVuelos")
    @ResponseWrapper(localName = "getVuelosResponse", targetNamespace = "http://ws.org/", className = "org.ws.GetVuelosResponse")
    @Action(input = "http://ws.org/OperacionesAerolinea/getVuelosRequest", output = "http://ws.org/OperacionesAerolinea/getVuelosResponse")
    public List<Vuelos> getVuelos();

    /**
     * 
     * @return
     *     returns java.util.List<org.ws.Clientes>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientes", targetNamespace = "http://ws.org/", className = "org.ws.GetClientes")
    @ResponseWrapper(localName = "getClientesResponse", targetNamespace = "http://ws.org/", className = "org.ws.GetClientesResponse")
    @Action(input = "http://ws.org/OperacionesAerolinea/getClientesRequest", output = "http://ws.org/OperacionesAerolinea/getClientesResponse")
    public List<Clientes> getClientes();

    /**
     * 
     * @param emailCliente
     * @param nombreCliente
     * @param apellidoCliente
     * @param nacionalidad
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nuevoCliente", targetNamespace = "http://ws.org/", className = "org.ws.NuevoCliente")
    @ResponseWrapper(localName = "nuevoClienteResponse", targetNamespace = "http://ws.org/", className = "org.ws.NuevoClienteResponse")
    @Action(input = "http://ws.org/OperacionesAerolinea/nuevoClienteRequest", output = "http://ws.org/OperacionesAerolinea/nuevoClienteResponse")
    public String nuevoCliente(
        @WebParam(name = "nombre_cliente", targetNamespace = "")
        String nombreCliente,
        @WebParam(name = "apellido_cliente", targetNamespace = "")
        String apellidoCliente,
        @WebParam(name = "email_cliente", targetNamespace = "")
        String emailCliente,
        @WebParam(name = "nacionalidad", targetNamespace = "")
        String nacionalidad);

    /**
     * 
     * @return
     *     returns java.util.List<org.ws.OrigenDestinoVuelos>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrigenDestino", targetNamespace = "http://ws.org/", className = "org.ws.GetOrigenDestino")
    @ResponseWrapper(localName = "getOrigenDestinoResponse", targetNamespace = "http://ws.org/", className = "org.ws.GetOrigenDestinoResponse")
    @Action(input = "http://ws.org/OperacionesAerolinea/getOrigenDestinoRequest", output = "http://ws.org/OperacionesAerolinea/getOrigenDestinoResponse")
    public List<OrigenDestinoVuelos> getOrigenDestino();

    /**
     * 
     * @param idBoleto
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelarBoleto", targetNamespace = "http://ws.org/", className = "org.ws.CancelarBoleto")
    @ResponseWrapper(localName = "cancelarBoletoResponse", targetNamespace = "http://ws.org/", className = "org.ws.CancelarBoletoResponse")
    @Action(input = "http://ws.org/OperacionesAerolinea/cancelarBoletoRequest", output = "http://ws.org/OperacionesAerolinea/cancelarBoletoResponse")
    public boolean cancelarBoleto(
        @WebParam(name = "id_boleto", targetNamespace = "")
        int idBoleto);

}
