/* create user Diego identified by root;
grant connect to Diego;
grant all privileges to Diego; */

drop table BOLETOS_COMPRADOS_AGENCIA;
drop table AEROLINEAS;
drop table CLIENTE;
drop table DATOS_AGENCIA_VIAJES;
drop table USUARIOS_AGENCIA;
drop table VIAJES;

--------------------------------------------------------
--  DDL for Table AEROLINEAS
--------------------------------------------------------
  CREATE TABLE "DIEGO"."AEROLINEAS" 
   (	"ID_AEROLINEA" NUMBER(11,0), 
	"NOMBRE_AEROLINEA" VARCHAR2(50 BYTE), 
	"EMAIL_AEROLINEA" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  DDL for Table BOLETOS_COMPRADOS_AGENCIA
--------------------------------------------------------
/* El de abajo está comentado porque ahora se quiere crear
una tabla de Boletos_Comprados_Agencia sin la llave foránea hacia
la tabla Cliente, debido a que se quieren registrar todas estas compras
sin guardar registro de los clientes en la DB de la agencia, sino solo
registrándolos y consultándolos con el WS cliente que conecta 
hacia el WS server. Así no hay gran clavo. */
CREATE TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA" 
   (	"ID_BOLETO_COMPRADO_AGENCIA" NUMBER(11,0), 
	"ID_CLIENTE_AEROLINEA" NUMBER(11,0), 
	"ID_AEROLINEA" NUMBER(11,0), 
	"BOLETO_CANCELADO" NUMBER(1,0), 
	"NO_BOLETO" NUMBER(11,0), 
	"FECHA_COMPRA_BOLETO" DATE, 
	"FECHA_BOLETO_CANCELADO_AGENCIA" DATE,
    "USUARIO_AGENCIA" VARCHAR2(50 BYTE),
    "ID_VIAJE_AGENCIA" NUMBER(11,0)
    
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  

  CREATE TABLE VIAJES
(
    id_viaje_agencia number(11) not null,
    origen_viaje varchar2(50),
    destino_viaje varchar2(50),
    precio_total_vuelos number(11,2) default 0,
    constraint viaje_pk 
        primary key (id_viaje_agencia)
);
  /*
  CREATE TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA" 
   (	"ID_BOLETO_COMPRADO_AGENCIA" NUMBER(11,0), 
	"ID_CLIENTE_AGENCIA" NUMBER(11,0), 
	"ID_AEROLINEA" NUMBER(11,0), 
	"BOLETO_CANCELADO" NUMBER(1,0), 
	"NO_BOLETO" NUMBER(11,0), 
	"FECHA_COMPRA_BOLETO" DATE, 
	"FECHA_BOLETO_CANCELADO_AGENCIA" DATE 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  */
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "DIEGO"."CLIENTE" 
   (	"ID_CLIENTE_AGENCIA" NUMBER(11,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"NACIONALIDAD" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DATOS_AGENCIA_VIAJES
--------------------------------------------------------

  CREATE TABLE "DIEGO"."DATOS_AGENCIA_VIAJES" 
   (	"ID_DATOS_AGENCIA_VIAJES" NUMBER(11,0), 
	"NOMBRE_AGENCIA" VARCHAR2(250 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIOS_AGENCIA
--------------------------------------------------------

  CREATE TABLE "DIEGO"."USUARIOS_AGENCIA" 
   (	"USUARIO_AGENCIA" VARCHAR2(50 BYTE),
	"CONTRA_AGENCIA" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
REM INSERTING into SYS.AEROLINEAS
SET DEFINE OFF;
REM INSERTING into SYS.BOLETOS_COMPRADOS_AGENCIA
SET DEFINE OFF;
REM INSERTING into SYS.CLIENTE
SET DEFINE OFF;
REM INSERTING into SYS.DATOS_AGENCIA_VIAJES
SET DEFINE OFF;
REM INSERTING into SYS.USUARIOS_AGENCIA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AEROLINEAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DIEGO"."AEROLINEAS_PK" ON "DIEGO"."AEROLINEAS" ("ID_AEROLINEA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOLETOS_COMPRADOS_AGENCIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DIEGO"."BOLETOS_COMPRADOS_AGENCIA_PK" ON "DIEGO"."BOLETOS_COMPRADOS_AGENCIA" ("ID_BOLETO_COMPRADO_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DIEGO"."CLIENTE_PK" ON "DIEGO"."CLIENTE" ("ID_CLIENTE_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DATOS_AGENCIA_VIAJES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DIEGO"."DATOS_AGENCIA_VIAJES_PK" ON "DIEGO"."DATOS_AGENCIA_VIAJES" ("ID_DATOS_AGENCIA_VIAJES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_AGENCIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DIEGO"."USUARIOS_AGENCIA_PK" ON "DIEGO"."USUARIOS_AGENCIA" ("USUARIO_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AEROLINEAS
--------------------------------------------------------

  ALTER TABLE "DIEGO"."AEROLINEAS" ADD CONSTRAINT "AEROLINEAS_PK" PRIMARY KEY ("ID_AEROLINEA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DIEGO"."AEROLINEAS" MODIFY ("ID_AEROLINEA" NOT NULL ENABLE);
 
  ALTER TABLE "DIEGO"."AEROLINEAS" MODIFY ("NOMBRE_AEROLINEA" NOT NULL ENABLE);
 
  ALTER TABLE "DIEGO"."AEROLINEAS" MODIFY ("EMAIL_AEROLINEA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOLETOS_COMPRADOS_AGENCIA
--------------------------------------------------------

  ALTER TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA" ADD CONSTRAINT "BOLETOS_COMPRADOS_AGENCIA_PK" PRIMARY KEY ("ID_BOLETO_COMPRADO_AGENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA" MODIFY ("ID_BOLETO_COMPRADO_AGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA" MODIFY ("ID_CLIENTE_AGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA" MODIFY ("ID_AEROLINEA" NOT NULL ENABLE);
 
  ALTER TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA" MODIFY ("NO_BOLETO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "DIEGO"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE_AGENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DIEGO"."CLIENTE" MODIFY ("ID_CLIENTE_AGENCIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DATOS_AGENCIA_VIAJES
--------------------------------------------------------

  ALTER TABLE "DIEGO"."DATOS_AGENCIA_VIAJES" ADD CONSTRAINT "DATOS_AGENCIA_VIAJES_PK" PRIMARY KEY ("ID_DATOS_AGENCIA_VIAJES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "DIEGO"."DATOS_AGENCIA_VIAJES" MODIFY ("ID_DATOS_AGENCIA_VIAJES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS_AGENCIA
--------------------------------------------------------

  ALTER TABLE "DIEGO"."USUARIOS_AGENCIA" MODIFY ("USUARIO_AGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "DIEGO"."USUARIOS_AGENCIA" MODIFY ("USUARIO_AGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "DIEGO"."USUARIOS_AGENCIA" MODIFY ("CONTRA_AGENCIA" NOT NULL ENABLE);
 
  ALTER TABLE "DIEGO"."USUARIOS_AGENCIA" ADD CONSTRAINT "USUARIOS_AGENCIA_PK" PRIMARY KEY ("USUARIO_AGENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  
  /*
    ALTER TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA"
    ADD CONSTRAINT BOLETOS_COMPRADOS_AGENCIA_FK0
    FOREIGN KEY ("ID_CLIENTE_AGENCIA")
    REFERENCES "DIEGO"."CLIENTE" ("ID_CLIENTE_AGENCIA");
    */
    
    ALTER TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA"
    ADD CONSTRAINT BOLETOS_COMPRADOS_AGENCIA_FK1
    FOREIGN KEY ("ID_AEROLINEA")
    REFERENCES "DIEGO"."AEROLINEAS" ("ID_AEROLINEA");
    
    ALTER TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA"
    ADD CONSTRAINT BOLETOS_COMPRADOS_AGENCIA_FK2
    FOREIGN KEY ("USUARIO_AGENCIA")
    REFERENCES "DIEGO"."USUARIOS_AGENCIA" ("USUARIO_AGENCIA");
    
    ALTER TABLE "DIEGO"."BOLETOS_COMPRADOS_AGENCIA"
    ADD CONSTRAINT BOLETOS_COMPRADOS_AGENCIA_FK3
    FOREIGN KEY ("ID_VIAJE_AGENCIA")
    REFERENCES "DIEGO"."VIAJES" ("ID_VIAJE_AGENCIA");
    
    /*  
    CONSTRAINT "BOLETOS_COMPRADOS_AGENCIA_FK0" FOREIGN KEY ("ID_CLIENTE_AGENCIA")
    REFERENCES "DIEGO"."CLIENTE" ("ID_CLIENTE_AGENCIA") ENABLE, 
    CONSTRAINT "BOLETOS_COMPRADOS_AGENCIA_FK1" FOREIGN KEY ("ID_AEROLINEA")
    REFERENCES "DIEGO"."AEROLINEA" ("ID_AEROLINEA") ENABLE */

drop sequence boletos_comprados_seq;
create sequence boletos_comprados_seq START WITH 1;

drop trigger boletos_comprados_bi_ai;
create or replace trigger boletos_comprados_bi_ai
before insert on boletos_comprados_agencia
for each row
begin
    select boletos_comprados_seq.NEXTVAL
    into :new.id_boleto_comprado_agencia
    from dual;
end;
/ 